version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: contentful
    versions:
    - 8.1.7
    - 8.1.8
    - 8.1.9
    - 8.2.0
    - 8.2.1
    - 8.3.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-icons
    versions:
    - 4.1.0
  - dependency-name: react
    versions:
    - 17.0.1
